import img1 from './images/images111.png';
import img2 from './images/Rectangle 12.png';
import img3 from './images/Rectangle 13.png';

export const kurpalar = [
  {
    id: 1,
    title: "The Royal",
    price: "$1249",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Royal matrasimiz bilan qirollik uyqusini his eting.",
    text: "Yuqori sifatli po’lat buloqlar va mustahkamlangan qirralar bilan uzoq muddatli qo‘llab-quvvatlash ta’minlaydi.",
    textes: "Qirollik darajasidagi qulaylik.",
  },
  {
    id: 2,
    title: "Premium Comfort",
    price: "$1149",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Extra qulaylik va yumshoqlik.",
    text: "Ushbu matras tanaga moslashib, optimal bosim taqsimotini ta’minlaydi.",
    textes: "Ortopedik qulaylik bilan sog‘lom uyqu.",
  },
  {
    id: 3,
    title: "Memory Foam",
    price: "$999",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Shaxsiy moslashuv va bosimni kamaytirish.",
    text: "Issiqlik ta’sirida shaklini o‘zgartirib, maksimal qulaylik yaratadi.",
    textes: "Memory foam bilan ideal yotish holati.",
  },
  {
    id: 4,
    title: "Ortho Care",
    price: "$899",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Ortopedik qo‘llab-quvvatlash bilan bel uchun ideal.",
    text: "Ortopedik xususiyatlarga ega bo‘lib, bel va orqa og‘riqlarini kamaytiradi.",
    textes: "Tana tuzilishiga mos qo‘llab-quvvatlash.",
  },
  {
    id: 5,
    title: "Luxury Plush",
    price: "$1349",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Maksimal yumshoqlik va nafislik.",
    text: "Super-yumshoq qatlamlar bilan hashamatli his beradi.",
    textes: "Mehmonxona darajasidagi qulaylik.",
  },
  {
    id: 6,
    title: "Cooling Gel",
    price: "$1099",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Sovutuvchi texnologiya bilan yozgi uyqu uchun ideal.",
    text: "Haroratni nazorat qilib, ortiqcha issiqlikni kamaytiradi.",
    textes: "Harorat nazorati bilan tetik uyg‘oning.",
  },
  {
    id: 7,
    title: "Hybrid Comfort",
    price: "$1249",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Ikki qatlamli texnologiya bilan qo‘llab-quvvatlash.",
    text: "Memory foam va bahor buloqlari kombinatsiyasi.",
    textes: "Mukammal balans va yostiq qo‘llab-quvvatlash.",
  },
  {
    id: 8,
    title: "Eco-Friendly Bamboo",
    price: "$949",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Tabiiy bambuk tolalaridan tayyorlangan.",
    text: "Antibakterial va allergiyaga mos matras.",
    textes: "Sog‘lom va ekologik toza uyqu.",
  },
  {
    id: 9,
    title: "Aloe Vera Infused",
    price: "$999",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Aloe Vera ekstrakti bilan qulaylik.",
    text: "Tabiiy shifobaxsh xususiyatlarga ega material.",
    textes: "Sog‘lom uyqu uchun Aloe Vera bilan maxsus matras.",
  }
];
