import img1 from './images/images111.png';
import img2 from './images/Rectangle 12.png';
import img3 from './images/Rectangle 13.png';

export const topperlar = [
  {
    id: 1,
    title: "Premium Comfort",
    price: "$349",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Super yumshoq qulaylik bilan uxlang.",
    text: "Ushbu topper tanangizga moslashib, bosimni kamaytiradi.",
    textes: "Premium Comfort bilan orom oling.",
  },
  {
    id: 2,
    title: "Memory Foam",
    price: "$299",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Bosimni kamaytiruvchi memory foam texnologiyasi.",
    text: "Issiqlikka moslashuvchi material yotish qulayligini oshiradi.",
    textes: "O'zingizga mos keladigan shaklga ega topper.",
  },
  {
    id: 3,
    title: "Luxury Plush",
    price: "$399",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Extra qulaylik va nafislik.",
    text: "Balandligi 5 sm bo'lib, optimal yostiq qo‘llab-quvvatlash beradi.",
    textes: "Luxury Plush bilan o‘ziga xos yotish hissini his eting.",
  },
  {
    id: 4,
    title: "Orthopedic Support",
    price: "$279",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Ortopedik yordam va qo‘llab-quvvatlash.",
    text: "Ushbu topper bel og‘rig‘ini kamaytirishga yordam beradi.",
    textes: "Ortopedik qo‘llab-quvvatlash bilan yaxshiroq uxlang.",
  },
  {
    id: 5,
    title: "Cooling Gel",
    price: "$359",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Sovutuvchi gel qatlami bilan yozgi qulaylik.",
    text: "Haroratni nazorat qilib, haddan tashqari issiqlikni oldini oladi.",
    textes: "Sovutuvchi gel bilan tetik uyg'oning.",
  },
  {
    id: 6,
    title: "Eco-Friendly Bamboo",
    price: "$329",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Ekologik toza materiallardan tayyorlangan.",
    text: "Bakteriyalarga qarshi va allergiyaga mos keladi.",
    textes: "Tabiiy va sog‘lom uyqu uchun ideal tanlov.",
  },
  {
    id: 7,
    title: "Ultra Soft Feather",
    price: "$379",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "G‘oz patlari kabi yumshoq yostiqcha.",
    text: "Yuqori sifatli materiallar bilan qulaylik ta'minlaydi.",
    textes: "Ultra yumshoqlik bilan orom oling.",
  },
  {
    id: 8,
    title: "Dual Layer Hybrid",
    price: "$389",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Ikki qatlamli texnologiya bilan qo‘llab-quvvatlash.",
    text: "Memory foam va buloqli qatlam kombinatsiyasi.",
    textes: "Hybrid texnologiya bilan mukammal yotish tajribasi.",
  },
  {
    id: 9,
    title: "Aloe Vera Infused",
    price: "$299",
    img1: img1,
    img2: img2,
    img3: img3,
    label: "Aloe Vera ekstrakti bilan namlantiruvchi ta’sir.",
    text: "Tabiiy shifobaxsh xususiyatlarga ega material.",
    textes: "Sog‘lom uyqu uchun Aloe Vera bilan maxsus topper.",
  }
];
